# Generated by Django 3.2 on 2021-06-12 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaseLogicaProgramacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('categoria', models.CharField(blank=True, choices=[('O', 'Operadores'), ('ES', 'Entrada e Saída de Dados'), ('C', 'Condicional'), ('R', 'Laço de repetição')], max_length=2, null=True, verbose_name='Categoria da fase')),
                ('pontos', models.IntegerField(verbose_name='Pontos da fase')),
                ('questao', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='questao.questao', verbose_name='Questão da fase')),
            ],
            options={
                'verbose_name': 'Fase Logica de Programacao',
                'verbose_name_plural': 'Fases Logica de Programacao',
            },
        ),
        migrations.CreateModel(
            name='FasePensamentoComputacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('categoria', models.CharField(blank=True, choices=[('D', 'Definicao'), ('A', 'Algoritimo'), ('L', 'Logica')], max_length=2, null=True, verbose_name='Categoria da fase')),
                ('pontos', models.IntegerField(verbose_name='Pontos da fase')),
                ('questao', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='questao.questao', verbose_name='Questão da fase')),
            ],
            options={
                'verbose_name': 'Fase Pensamento Computacional',
                'verbose_name_plural': 'Fases Pensamento Computacional',
            },
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('pontuacao', models.IntegerField(blank=True, verbose_name='Pontuação do jogador')),
                ('nivel', models.IntegerField(blank=True, null=True, verbose_name='Nível do jogador')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
            },
        ),
        migrations.CreateModel(
            name='JogadorTurmaFasePensamentoComputacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jogador.fasepensamentocomputacional', verbose_name='Fase PEnsamento Computacional')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jogador.jogador', verbose_name='Jogador')),
            ],
            options={
                'verbose_name': 'Jogador Turma Fase Pensamento Computacional',
                'verbose_name_plural': 'Jogadores Turmas Fases Pensamento Computacional',
            },
        ),
        migrations.CreateModel(
            name='JogadorTurmaFaseLogicaProgramacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jogador.faselogicaprogramacao', verbose_name='Fase Lógica Programação')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jogador.jogador', verbose_name='Jogador')),
            ],
            options={
                'verbose_name': 'Jogador Turma Fase Logica Programacao',
                'verbose_name_plural': 'Jogadores Turmas Fases Logica Programaca',
            },
        ),
    ]
