# Generated by Django 3.2 on 2021-05-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('pontuacao', models.IntegerField(blank=True, verbose_name='Pontuação do jogador')),
                ('faseatualpensamentocomputacional', models.IntegerField(verbose_name='Fase atual pensamento computacional')),
                ('faseatuallogicaprogramacao', models.IntegerField(verbose_name='Fase atual logica programação')),
                ('faseatualraciociniologico', models.IntegerField(verbose_name='Fase atual raciocinio logico')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
