# Generated by Django 3.2 on 2021-06-02 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questao', '0001_initial'),
        ('jogador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FasePensamentoComputacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('categoria', models.CharField(blank=True, choices=[('D', 'Definicao'), ('A', 'Algoritimo'), ('L', 'Logica')], max_length=2, null=True, verbose_name='Categoria da fase')),
                ('pontos', models.IntegerField(verbose_name='Pontos da fase')),
                ('questao', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='questao.questao', verbose_name='Questão da fase')),
            ],
            options={
                'verbose_name': 'Fase Pensamento Computacional',
                'verbose_name_plural': 'Fases Pensamento Computacional',
            },
        ),
        migrations.CreateModel(
            name='JogadorTurmaFasePensamentoComputacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jogador.fasepensamentocomputacional', verbose_name='Fase PEnsamento Computacional')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jogador.jogador', verbose_name='Jogador')),
            ],
            options={
                'verbose_name': 'Jogador Turma Fase Pensamento Computacional',
                'verbose_name_plural': 'Jogadores Turmas Fases Pensamento Computacional',
            },
        ),
    ]
