# Generated by Django 3.2 on 2021-06-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fasepensamentocomputacional',
            name='questao',
        ),
        migrations.RemoveField(
            model_name='jogadorturmafaselogicaprogramacao',
            name='fase',
        ),
        migrations.RemoveField(
            model_name='jogadorturmafaselogicaprogramacao',
            name='jogador',
        ),
        migrations.RemoveField(
            model_name='jogadorturmafasepensamentocomputacional',
            name='fase',
        ),
        migrations.RemoveField(
            model_name='jogadorturmafasepensamentocomputacional',
            name='jogador',
        ),
        migrations.AddField(
            model_name='jogador',
            name='faselogicaprogramacao',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Fase lógica de programação'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='fasepensamentocomputacional',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Fase lógica de programação'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='nivel',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Nível do jogador'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='pontuacao',
            field=models.IntegerField(blank=True, default=0, verbose_name='Pontuação do jogador'),
        ),
        migrations.DeleteModel(
            name='FaseLogicaProgramacao',
        ),
        migrations.DeleteModel(
            name='FasePensamentoComputacional',
        ),
        migrations.DeleteModel(
            name='JogadorTurmaFaseLogicaProgramacao',
        ),
        migrations.DeleteModel(
            name='JogadorTurmaFasePensamentoComputacional',
        ),
    ]
