# Generated by Django 3.2 on 2021-06-12 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('descricao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descrição da opção')),
                ('correta', models.BooleanField(blank=True, verbose_name='Opção correta')),
            ],
            options={
                'verbose_name': 'Opção',
                'verbose_name_plural': 'Opções',
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título da questão')),
                ('url_img', models.CharField(max_length=150, verbose_name='Descrição da questão')),
                ('opcao1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Opcao1', to='questao.opcao', verbose_name='Opção 1')),
                ('opcao2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Opcao2', to='questao.opcao', verbose_name='Opção 2')),
                ('opcao3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Opcao3', to='questao.opcao', verbose_name='Opção 3')),
                ('opcao4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Opcao4', to='questao.opcao', verbose_name='Opção 4')),
            ],
            options={
                'verbose_name': 'Questao',
                'verbose_name_plural': 'Questoes',
            },
        ),
    ]
