# Generated by Django 3.2 on 2021-06-15 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Título de conteúdo')),
                ('url_img', models.CharField(blank=True, max_length=150, verbose_name='Imagem do conteúdo')),
                ('questao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Questão', to='questao.questao', verbose_name='Questão do conteúdo')),
            ],
            options={
                'verbose_name': 'Conteúdo',
                'verbose_name_plural': 'Conteúdos',
            },
        ),
    ]
