# Generated by Django 3.2 on 2021-06-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='modulo',
            field=models.CharField(blank=True, choices=[('P', 'Pensamento computacional'), ('L', 'Lógica de programação')], max_length=1, null=True, verbose_name='Módulo'),
        ),
    ]
