# Generated by Django 3.2 on 2021-06-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='codigoTurma',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Código da turma'),
        ),
    ]
